version: '3.8'

services:
  telegrambot:
    build: .
    container_name: restrictbot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: restrictbot_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
